### ISSUE TITLE
Docker documentation ?

### ISSUE THREAD

**Issue by prigal** [CasperVerswijvelt/google-photos-backup#3]
Hello (again !)

Reading your code, I'm guessing that I have to mount 2 volumes /session and /download and I have to setup some ENV variables to make everything work. I see that you integrate some cronjob in the container, so I guess I have the choice to keep the container running with a cron or launch it by myself. 

Maybe you could add a docker-compose file to the project and a quick note in the readme to explain how to setup and run everything correctly ?

Thank you !

**Comment by prigal** [comment]
For future ref.

```
version: "3"
services:
  googlephotobackup:
    build: .
    environment:
      - CRON=${CRON}
      - HEALTHCHECK_HOST=${HEALTHCHECK_HOST}
      - HEALTHCHECK_ID=${HEALTHCHECK_ID}
      - INITIAL_PHOTO_URL=${INITIAL_PHOTO_URL}
      - WRITE_SCRAPED_EXIF=${WRITE_SCRAPED_EXIF}
      - FLAT_DIRECTORY_STRUCTURE=${FLAT_DIRECTORY_STRUCTURE}

    volumes:
      - ./session:/session
      - ./library:/download
    restart: unless-stopped
```
